name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install node packages
        run: npm install
      - name: Check eslint
        run: npm run check:lint

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install node packages
        run: npm install
      - name: Check prettier
        run: npm run check:prettier
